package com.andreinsigne.redditclientapp.ui.redditpostaction

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditPostActionInjector {
    fun inject(fragment: RedditPostActionFragment)
}


/**
 * RedditPostActionInjector injector implementation of the protocol template for injection
 **/
class RedditPostActionInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditPostActionFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditPostActionFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditPostActionPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
