package com.andreinsigne.redditclientapp.ui.redditauthsign

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditAuthSignInjector {
    fun inject(fragment: RedditAuthSignFragment)
}


/**
 * RedditAuthSignInjector injector implementation of the protocol template for injection
 **/
class RedditAuthSignInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditAuthSignFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditAuthSignFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditAuthSignPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
