package com.andreinsigne.redditclientapp.ui.redditmenu

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditMenuInjector {
    fun inject(fragment: RedditMenuFragment)
}


/**
 * RedditMenuInjector injector implementation of the protocol template for injection
 **/
class RedditMenuInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditMenuFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditMenuFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditMenuPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
