package com.andreinsigne.redditclientapp.ui.redditinbox

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditInboxInjector {
    fun inject(fragment: RedditInboxFragment)
}


/**
 * RedditInboxInjector injector implementation of the protocol template for injection
 **/
class RedditInboxInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditInboxFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditInboxFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditInboxPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
