package com.andreinsigne.redditclientapp.ui.redditpostfeed

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditPostFeedInjector {
    fun inject(fragment: RedditPostFeedFragment)
}


/**
 * RedditPostFeedInjector injector implementation of the protocol template for injection
 **/
class RedditPostFeedInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditPostFeedFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditPostFeedFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditPostFeedPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
