package com.andreinsigne.redditclientapp.model

import kotlinx.serialization.Serializable


@Serializable
data class Me(var has_external_account: Boolean = false,
                    var user_is_banned: Boolean = false,
                    var user_is_contributor: Boolean = false,
                    var banner_img: String? = null,
                    var show_media: Boolean = false,
                    var community_icon: String? = null,
                    var display_name: String? = null,
                    var display_name_prefixed: String? = null,
                    var header_img: String? = null,
                    var title: String? = null,
                    var icon_img: String? = null,
                    var coins: Int = 0,
                    var over_18: Boolean = false,
                    var subscribers: Int = 0,
                    var is_default_icon: Boolean = false,
                    var name: String? = null,
                    var is_default_banner: Boolean = false,
                    var url: String? = null,
                    var user_is_moderator: Boolean = false,
                    var public_description: String? = null,
                    var description: String? = null,
                    var comment_karma: Int = 0,
                    var link_karma: Int = 0,
                    var created_utc: Double = 0.0,
                    var subreddit : SubredditData? = null,
                    var data : MeData? = null)
@Serializable
data class MeData(var has_external_account: Boolean = false,
                  var user_is_banned: Boolean = false,
                  var user_is_contributor: Boolean = false,
                  var banner_img: String? = null,
                  var show_media: Boolean = false,
                  var community_icon: String? = null,
                  var display_name: String? = null,
                  var display_name_prefixed: String? = null,
                  var header_img: String? = null,
                  var title: String? = null,
                  var icon_img: String? = null,
                  var coins: Int = 0,
                  var over_18: Boolean = false,
                  var subscribers: Int = 0,
                  var is_default_icon: Boolean = false,
                  var name: String? = null,
                  var is_default_banner: Boolean = false,
                  var url: String? = null,
                  var user_is_moderator: Boolean = false,
                  var public_description: String? = null,
                  var description: String? = null,
                  var comment_karma: Int = 0,
                  var link_karma: Int = 0,
                  var created_utc: Double = 0.0,
                  var subreddit : SubredditData? = null)

