package com.andreinsigne.redditclientapp.ui.chooseinterest

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface ChooseInterestInjector {
    fun inject(fragment: ChooseInterestFragment)
}


/**
 * ChooseInterestInjector injector implementation of the protocol template for injection
 **/
class ChooseInterestInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : ChooseInterestFragment generated by the MVPTemplate
     **/
    fun inject(fragment: ChooseInterestFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = ChooseInterestPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
