package com.andreinsigne.redditclientapp.ui.redditchat

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditChatInjector {
    fun inject(fragment: RedditChatFragment)
}


/**
 * RedditChatInjector injector implementation of the protocol template for injection
 **/
class RedditChatInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditChatFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditChatFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditChatPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
