package com.andreinsigne.redditclientapp.ui.redditdetailcomments

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditDetailCommentsInjector {
    fun inject(fragment: RedditDetailCommentsFragment)
}


/**
 * RedditDetailCommentsInjector injector implementation of the protocol template for injection
 **/
class RedditDetailCommentsInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditDetailCommentsFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditDetailCommentsFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditDetailCommentsPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
