package com.andreinsigne.redditclientapp.ui.redditpreview

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditPreviewInjector {
    fun inject(fragment: RedditPreviewFragment)
}


/**
 * RedditPreviewInjector injector implementation of the protocol template for injection
 **/
class RedditPreviewInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditPreviewFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditPreviewFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditPreviewPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
