package com.andreinsigne.redditclientapp.ui.redditbrowse

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditBrowseInjector {
    fun inject(fragment: RedditBrowseFragment)
}


/**
 * RedditBrowseInjector injector implementation of the protocol template for injection
 **/
class RedditBrowseInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditBrowseFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditBrowseFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditBrowsePresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
