package com.andreinsigne.redditclientapp.ui.redditaboutsub

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditAboutSubInjector {
    fun inject(fragment: RedditAboutSubFragment)
}


/**
 * RedditAboutSubInjector injector implementation of the protocol template for injection
 **/
class RedditAboutSubInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditAboutSubFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditAboutSubFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditAboutSubPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
