package com.andreinsigne.redditclientapp.ui.redditabout

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditAboutInjector {
    fun inject(fragment: RedditAboutFragment)
}


/**
 * RedditAboutInjector injector implementation of the protocol template for injection
 **/
class RedditAboutInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditAboutFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditAboutFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditAboutPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
