package com.andreinsigne.redditclientapp.ui.redditmessages

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditMessagesInjector {
    fun inject(fragment: RedditMessagesFragment)
}


/**
 * RedditMessagesInjector injector implementation of the protocol template for injection
 **/
class RedditMessagesInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditMessagesFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditMessagesFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditMessagesPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
