package com.andreinsigne.redditclientapp.ui.redditfeedview

import com.andreinsigne.redditclientapp.data.DataInjector
import com.andreinsigne.redditclientapp.manager.ServicesInjector
import com.andreinsigne.redditclientapp.manager.APIManager
import com.andreinsigne.redditclientapp.manager.AuthManager

/**
 * injector interface template for injection of the services and data
 **/
interface RedditFeedViewInjector {
    fun inject(fragment: RedditFeedViewFragment)
}


/**
 * RedditFeedViewInjector injector implementation of the protocol template for injection
 **/
class RedditFeedViewInjectorImplementation() {

    /**
     * injects the ___VARIABLE_moduleName___ViewController generated with the services and the
     * presenter used data
     * @param fragment : RedditFeedViewFragment generated by the MVPTemplate
     **/
    fun inject(fragment: RedditFeedViewFragment) {
        val data = DataInjector().data
        val services = ServicesInjector(data)
        val presenter = RedditFeedViewPresenterImplementation(fragment, services.getAPI(), services.getAuth())
        fragment.presenter = presenter
    }


}
